import re

from app.rag import TradeOpsRAG


def extract_cited_sources(answer):
    """
    Extract source numbers from citations generated by the LLM.

    Supports:

        [Source 1]
        [Source 1, Source 2]
        [Source 1, Source 2, Source 3]

    Returns:
        Sorted list of unique source numbers.
    """

    source_numbers = set()

    matches = re.findall(
        r"Source\s+(\d+)",
        answer,
        flags=re.IGNORECASE
    )

    for number in matches:

        source_numbers.add(
            int(number)
        )

    return sorted(source_numbers)


def is_no_information_answer(answer):
    """
    Determine whether the model is saying that the
    requested information was not found.
    """

    answer_lower = answer.lower()

    phrases = [
        "i could not find this information",
        "could not find this information",
        "i could not find enough information",
        "could not find enough information",
        "not found in the provided documents",
        "not available in the provided documents",
        "cannot find this information",
        "do not contain this information",
        "does not contain this information",
    ]

    return any(
        phrase in answer_lower
        for phrase in phrases
    )


def remove_citations(answer):
    """
    Remove citations from an answer.

    Example:

        Some answer. [Source 1, Source 2]

    becomes:

        Some answer.
    """

    cleaned = re.sub(
        r"\[\s*Source\s+\d+(?:\s*,\s*Source\s+\d+)*\s*\]",
        "",
        answer,
        flags=re.IGNORECASE
    )

    return cleaned.strip()


def clean_answer(answer):
    """
    Clean the final LLM response.

    If the model says the information is not available,
    citations are removed because they do not support an
    answer that wasn't found.
    """

    answer = answer.strip()

    if is_no_information_answer(answer):

        answer = remove_citations(answer)

    return answer


def build_conversation_context(history, max_turns=4):
    """
    Build a lightweight conversation context.

    Only the most recent turns are retained so that the
    prompt does not grow indefinitely.

    Args:
        history:
            List of previous conversation turns.

        max_turns:
            Maximum number of previous user/assistant
            exchanges to include.

    Returns:
        String containing recent conversation context.
    """

    if not history:

        return ""

    recent_history = history[-max_turns:]

    context_parts = []

    for turn in recent_history:

        context_parts.append(
            f"""
User:
{turn["user"]}

Assistant:
{turn["assistant"]}
"""
        )

    return "\n".join(context_parts)


def rewrite_follow_up_question(
    query,
    conversation_context
):
    """
    Ask the LLM to rewrite a follow-up question into a
    standalone question.

    This is useful for questions such as:

        User:
        How are trade breaks investigated?

        User:
        What data do they validate?

    The second query becomes something like:

        What data do analysts validate when investigating
        trade breaks?

    If there is no previous conversation, the original
    query is returned unchanged.
    """

    if not conversation_context:

        return query

    prompt = f"""
You are a query-rewriting component for a TradeOps
document retrieval system.

Your task is to rewrite the user's latest question into
a standalone search query.

Use the previous conversation only to resolve references
such as:

- it
- they
- them
- this
- that
- those
- the process
- the issue
- the above

Do NOT answer the question.

Do NOT add information that is not present in the
conversation.

If the user's question is already standalone, return it
unchanged.

Return ONLY the rewritten question.

PREVIOUS CONVERSATION:

{conversation_context}

LATEST USER QUESTION:

{query}

STANDALONE SEARCH QUERY:
"""

    try:

        from app.llm import generate_response

        rewritten_query = generate_response(
            prompt
        ).strip()

        if not rewritten_query:

            return query

        return rewritten_query

    except Exception:

        # If rewriting fails, fall back to the original
        # question rather than breaking the RAG pipeline.

        return query


def main():

    print("=" * 70)
    print("TRADEOPS RAG ASSISTANT")
    print("=" * 70)

    print("\nInitializing RAG system...\n")

    rag = TradeOpsRAG()

    # ---------------------------------------------------------
    # Conversation memory
    # ---------------------------------------------------------

    conversation_history = []

    print("\n" + "=" * 70)
    print("READY")
    print("=" * 70)

    print(
        "\nAsk questions about the TradeOps documentation."
    )

    print(
        "Follow-up questions are supported."
    )

    print(
        "Type 'exit' or 'quit' to close the assistant."
    )

    print()

    while True:

        try:

            query = input("You: ").strip()

        except (KeyboardInterrupt, EOFError):

            print(
                "\n\nExiting TradeOps RAG Assistant."
            )

            break

        # Ignore empty input

        if not query:

            continue

        # -----------------------------------------------------
        # Exit commands
        # -----------------------------------------------------

        if query.lower() in {
            "exit",
            "quit"
        }:

            print(
                "\nExiting TradeOps RAG Assistant."
            )

            break

        print(
            "\nSearching TradeOps knowledge base..."
        )

        try:

            # -------------------------------------------------
            # Build recent conversation context
            # -------------------------------------------------

            conversation_context = (
                build_conversation_context(
                    conversation_history
                )
            )

            # -------------------------------------------------
            # Rewrite follow-up question
            # -------------------------------------------------

            retrieval_query = (
                rewrite_follow_up_question(
                    query=query,
                    conversation_context=conversation_context
                )
            )

            # -------------------------------------------------
            # Run RAG
            # -------------------------------------------------

            answer, sources = rag.ask(
                query=retrieval_query,
                top_k=5,
                max_context_chunks=2
            )

            # -------------------------------------------------
            # Clean answer
            # -------------------------------------------------

            answer = clean_answer(
                answer
            )

            # -------------------------------------------------
            # Extract citations
            # -------------------------------------------------

            cited_source_numbers = (
                extract_cited_sources(
                    answer
                )
            )

            # -------------------------------------------------
            # Validate citations
            # -------------------------------------------------

            valid_source_numbers = {
                source["source_number"]
                for source in sources
            }

            verified_source_numbers = [
                number
                for number in cited_source_numbers
                if number in valid_source_numbers
            ]

            # Remove duplicates while preserving order

            verified_source_numbers = list(
                dict.fromkeys(
                    verified_source_numbers
                )
            )

            # -------------------------------------------------
            # Display answer
            # -------------------------------------------------

            print(
                "\n" + "-" * 70
            )

            print(
                "TRADEOPS ASSISTANT"
            )

            print(
                "-" * 70
            )

            print(
                answer
            )

            # -------------------------------------------------
            # Display verified sources
            # -------------------------------------------------

            print(
                "\n" + "-" * 70
            )

            print(
                "VERIFIED SOURCES"
            )

            print(
                "-" * 70
            )

            if verified_source_numbers:

                for source_number in (
                    verified_source_numbers
                ):

                    source = next(
                        (
                            item
                            for item in sources
                            if item["source_number"]
                            == source_number
                        ),
                        None
                    )

                    if source is None:

                        continue

                    print(
                        f"[Source {source_number}] "
                        f"{source['source']} — "
                        f"Page {source['page']}"
                    )

            else:

                print(
                    "No sources were explicitly cited."
                )

            # -------------------------------------------------
            # Store conversation turn
            # -------------------------------------------------

            conversation_history.append(
                {
                    "user": query,
                    "assistant": answer
                }
            )

            # Keep memory bounded.

            if len(conversation_history) > 10:

                conversation_history = (
                    conversation_history[-10:]
                )

            print()

        except Exception as error:

            print(
                "\nERROR:"
            )

            print(
                error
            )

            print(
                "\nThe assistant could not "
                "process this question."
            )


if __name__ == "__main__":

    main()